services:
  mongo:
    image: mongo:6
    container_name: digiconverter-mongo-dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data_dev:/data/db
    networks:
      - digiconverter-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    container_name: digiconverter-server-dev
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/logs:/app/logs
    networks:
      - digiconverter-network
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    container_name: digiconverter-client-dev
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:5000
      NODE_ENV: development
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - digiconverter-network
    restart: unless-stopped

volumes:
  mongo_data_dev:
    driver: local

networks:
  digiconverter-network:
    driver: bridge