services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    container_name: digiconverter-server-prod
    env_file:
      - ./server/.env.production
    volumes:
      - ./server/logs:/app/logs
    networks:
      - digiconverter-network
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    container_name: digiconverter-client-prod
    environment:
      NODE_ENV: production
    env_file:
      - ./server/.env.production
    depends_on:
      - backend
    networks:
      - digiconverter-network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: digiconverter-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    env_file:
      - ./server/.env.production
    depends_on:
      - backend
      - frontend
    networks:
      - digiconverter-network
    restart: always

networks:
  digiconverter-network:
    driver: bridge