services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    container_name: digiconverter-server-prod
    env_file:
      - ./server/.env.production
    environment:
      NODE_ENV: production
      PORT: 5000
    volumes:
      - ./server/logs:/app/logs
    networks:
      - digiconverter-network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: digiconverter-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - digiconverter-network
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
      args:
        VITE_API_BASE_URL: ""
    container_name: digiconverter-client-prod
    environment:
      NODE_ENV: production
    volumes:
      - frontend_build:/usr/share/nginx/html
    networks:
      - digiconverter-network
    restart: "no"

volumes:
  frontend_build:
    driver: local

networks:
  digiconverter-network:
    driver: bridge